'use client'
import Link from 'next/link'
import { useQuery } from '@tanstack/react-query'
import Header from '@/components/layout/Header'
import { Alert, Badge, ButtonLink, Card, Skeleton } from '@/components/ui'
import { MultiempresaService } from '@/services'

export default function MasterPage() {
  const { data, isLoading, error } = useQuery({ queryKey: ['master-empresas-v143'], queryFn: MultiempresaService.listarEmpresasMaster, retry: false })
  return <div className="vf-fadein"><Header title="Admin Master NexLabs" /><div className="p-4 md:p-6 space-y-5"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-[var(--vf-text)]">Painel master multiempresa</h1><p className="text-sm text-[var(--vf-text2)]">Cadastre empresas, admin da empresa, planos, assinaturas, teste sem prazo e isenção permanente.</p></div><div className="flex gap-2 flex-wrap"><ButtonLink href="/master/empresas/nova">Nova empresa</ButtonLink><ButtonLink href="/master/assinaturas" variant="secondary">Assinaturas</ButtonLink><ButtonLink href="/master/planos" variant="secondary">Planos</ButtonLink></div></div>{error && <Alert type="error">{(error as Error).message}</Alert>}<div className="grid grid-cols-1 md:grid-cols-4 gap-3"><Card className="p-4"><span className="text-xs text-[var(--vf-text3)]">Empresas</span><b className="block text-2xl text-[var(--vf-primary)]">{data?.length ?? 0}</b></Card><Card className="p-4"><span className="text-xs text-[var(--vf-text3)]">Ativas</span><b className="block text-2xl text-[var(--vf-success)]">{(data ?? []).filter((e:any)=>String(e.status||'ativa')==='ativa').length}</b></Card><Card className="p-4"><span className="text-xs text-[var(--vf-text3)]">Trial</span><b className="block text-2xl text-[var(--vf-secondary)]">{(data ?? []).filter((e:any)=>String(e.plano||'trial')==='trial').length}</b></Card><Card className="p-4"><span className="text-xs text-[var(--vf-text3)]">Usuários</span><b className="block text-2xl text-[var(--vf-primary)]">{(data ?? []).reduce((a:number,e:any)=>a+(e.usuarios?.length||0),0)}</b></Card></div>{isLoading ? <Skeleton className="h-64" /> : <Card className="p-0 overflow-hidden"><div className="overflow-x-auto"><table className="vf-table w-full text-sm"><thead><tr><th>Empresa</th><th>Código</th><th>Plano</th><th>Status</th><th>Usuários</th><th></th></tr></thead><tbody>{(data ?? []).map((e:any)=><tr key={e.id}><td><b>{e.nome_fantasia || e.nome}</b><div className="text-xs text-[var(--vf-text3)]">{e.email || e.responsavel}</div></td><td>{e.codigo_empresa || e.matricula_empresa || '-'}</td><td>{e.plano || 'trial'}</td><td><Badge color={String(e.status||'ativa')==='ativa'?'green':'red'}>{e.status || 'ativa'}</Badge></td><td>{e.usuarios?.length || 0}</td><td><Link href={`/master/empresas/${e.id}`} className="text-[var(--vf-primary)] font-bold">Abrir</Link></td></tr>)}</tbody></table></div></Card>}</div></div>
}
